version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:80"

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=TEST
      - MYSQL_PASSWORD=TEST
      - MYSQL_DATABASE=dbname
  
networks:
  default:
