CREATE OR REPLACE FUNCTION CALCULA_PRECIO_MENU(
V_ID_PLATO_PRINCIPAL PLATO_PRINCIPAL.ID_PLATO_PRINCIPAL%TYPE,
V_ID_PLATO_SECUNDARIO PLATO_SECUNDARIO.ID_PLATO_SECUNDARIO%TYPE,
V_ID_BEBIDA BEBIDAS.ID_BEBIDA%TYPE
)
RETURN NUMBER
IS
    RES NUMBER;
BEGIN
    DECLARE
        V_PRECIO_PLATO_PRINCIPAL NUMBER;
        V_PRECIO_PLATO_SECUNDARIO NUMBER;
        V_PRECIO_BEBIDA NUMBER;
    BEGIN
        SELECT PLATO_PRINCIPAL.PRECIO INTO V_PRECIO_PLATO_PRINCIPAL
        FROM PLATO_PRINCIPAL
        WHERE PLATO_PRINCIPAL.ID_PLATO_PRINCIPAL = V_ID_PLATO_PRINCIPAL;
       
        IF V_ID_PLATO_SECUNDARIO = 'null' THEN
            V_PRECIO_PLATO_SECUNDARIO:=0;
        ELSE
            SELECT PLATO_SECUNDARIO.PRECIO INTO V_PRECIO_PLATO_SECUNDARIO
            FROM PLATO_SECUNDARIO
            WHERE PLATO_SECUNDARIO.ID_PLATO_SECUNDARIO = V_ID_PLATO_SECUNDARIO;
        END IF;

        IF V_ID_BEBIDA = 'null' THEN
            V_PRECIO_BEBIDA:=0;
        ELSE
            SELECT BEBIDAS.PRECIO INTO V_PRECIO_BEBIDA
            FROM BEBIDAS
            WHERE BEBIDAS.ID_BEBIDA = V_ID_BEBIDA;
        END IF;

        RES := V_PRECIO_PLATO_PRINCIPAL + V_PRECIO_PLATO_SECUNDARIO + V_PRECIO_BEBIDA;
    END;
RETURN RES;
END;