/* FUNCIONES */

CREATE OR REPLACE FUNCTION DIA_DE_LA_SEMANA(FECHA_RECOGIDA DATE)
RETURN INTEGER
IS
DIA INTEGER;
BEGIN
DIA := (TO_CHAR(FECHA_RECOGIDA, 'D'));
RETURN DIA;
END DIA_DE_LA_SEMANA;
/

CREATE OR REPLACE FUNCTION CALCULA_PRECIO_MENU(V_ID_MENU MENUS.ID_MENU%TYPE)
RETURN NUMBER
IS
    RES NUMBER;
BEGIN
    DECLARE
        V_ID_PLA_PRIN VARCHAR2(30);
        V_ID_PLA_SEC VARCHAR2(30);
        V_ID_BEBIDA VARCHAR2(30);
        V_PRECIO_PLATO_PRINCIPAL NUMBER;
        V_PRECIO_PLATO_SECUNDARIO NUMBER;
        V_BEBIDA NUMBER;
    BEGIN
        SELECT ID_PLATO_PRINCIPAL INTO V_ID_PLA_PRIN
        FROM MENUS
        WHERE ID_MENU = V_ID_MENU;
        IF V_ID_PLA_PRIN = null then
            V_PRECIO_PLATO_PRINCIPAL:=0;
        ELSE
            SELECT PLATO_PRINCIPAL.PRECIO INTO V_PRECIO_PLATO_PRINCIPAL
            FROM MENUS,PLATO_PRINCIPAL
            WHERE MENUS.ID_PLATO_PRINCIPAL = PLATO_PRINCIPAL.ID_PLATO_PRINCIPAL AND MENUS.ID_MENU = V_ID_MENU;
        END IF;
        
        SELECT ID_PLATO_SECUNDARIO INTO V_ID_PLA_SEC
        FROM MENUS
        WHERE ID_MENU = V_ID_MENU;
        IF V_ID_PLA_SEC = null then
            V_PRECIO_PLATO_SECUNDARIO:=0;
        ELSE
            SELECT PLATO_SECUNDARIO.PRECIO INTO V_PRECIO_PLATO_SECUNDARIO
            FROM MENUS,PLATO_SECUNDARIO
            WHERE MENUS.ID_PLATO_SECUNDARIO= PLATO_SECUNDARIO.ID_PLATO_SECUNDARIO AND MENUS.ID_MENU = V_ID_MENU;
        END IF;
        
        SELECT ID_BEBIDA INTO V_ID_BEBIDA
        FROM MENUS
        WHERE ID_MENU = V_ID_MENU;
        IF V_ID_BEBIDA = NULL THEN
            V_BEBIDA:=0;
        ELSE
            SELECT BEBIDAS.PRECIO INTO V_BEBIDA
            FROM MENUS,BEBIDAS
            WHERE MENUS.ID_BEBIDA= BEBIDAS.ID_BEBIDA AND MENUS.ID_MENU = V_ID_MENU;
        END IF;
        
        RES := V_PRECIO_PLATO_PRINCIPAL + V_PRECIO_PLATO_SECUNDARIO + V_BEBIDA;
    END;
RETURN RES;
END;
/
CREATE OR REPLACE FUNCTION CALCULA_PRECIO_PEDIDO(V_ID_PEDIDO PEDIDOS.ID_PEDIDO%TYPE)
RETURN NUMBER
IS
    RES NUMBER;
BEGIN
    DECLARE
        V_ID_MENU VARCHAR2(30);
    BEGIN
        SELECT PEDIDOS.ID_MENU INTO V_ID_MENU
        FROM PEDIDOS
        WHERE ID_PEDIDO = V_ID_PEDIDO;
        RES := CALCULA_PRECIO_MENU(V_ID_MENU);
    END;
RETURN RES;
END;
/
CREATE OR REPLACE FUNCTION INGRESOS_DEL_DIA
RETURN NUMBER
IS
    RES NUMBER;
BEGIN
        SELECT SUM(CALCULA_PRECIO_PEDIDO(ID_PEDIDO)) INTO RES
        FROM PEDIDOS
        WHERE TO_DATE(TO_CHAR(FECHA_RECOGIDA,'DD/MM/YY')) = TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YY'));
RETURN RES;
END;
/